#!/usr/bin/env python3
"""Copies already-generated deliverable(s) into a version (pv-version skill).

Copies each --source path (a file already generated by the
how-to-compile.md procedure, in whichever step(s)) to
{workFolder}/versions/{xxxx}/files/, keeping its filename. More than one
--source is accepted for multi-step build processes that generate more than
one artifact (e.g. a web build + a rules PDF build), all part of the same
complete deliverable.

Prints ONLY a JSON on stdout with what was copied:

  {"copied": ["files/index-v00167.html"]}

If any --source path doesn't exist, exits with an error without copying
anything (so as not to leave a half-done release with only some of its
artifacts).

Usage:
  python copy-build-artifacts.py --xxxx 00001 --source src/_output/versions/index-v00167.html
  python copy-build-artifacts.py --xxxx 00001 --source out/game.html --source out/rules.pdf
"""

import argparse
import json
import shutil
import sys
from pathlib import Path


def repo_root() -> Path:
    # This script lives at {repo}/.claude/skills/pv-version/scripts/
    return Path(__file__).resolve().parents[4]


def load_work_folder(root: Path) -> str:
    context_path = root / ".claude" / "pv-context.json"
    if not context_path.is_file():
        raise SystemExit(
            f"Cannot find {context_path}. Run the pv-init skill before "
            "copying the deliverable."
        )

    context = json.loads(context_path.read_text(encoding="utf-8"))
    framework = context.get("framework")
    if not framework:
        raise SystemExit(
            f"{context_path} has no 'framework' section. Run the pv-init "
            "skill to complete it."
        )
    return framework.get("workFolder", "/")


def resolve_versions_dir(root: Path, work_folder_rel: str) -> Path:
    # workFolder is always relative to the repo root, whether or not it
    # carries a leading "/" (that's only a convention to make it visually
    # explicit) -- Path("/a") / "/b" would otherwise discard "a" entirely,
    # since pathlib treats a leading-slash operand as its own absolute path.
    work_root = root / (work_folder_rel or "").lstrip("/")
    return work_root / "versions"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--xxxx", required=True, help="Code of the version being prepared.")
    parser.add_argument(
        "--source",
        required=True,
        action="append",
        help="Path (relative to the repo root) of a generated artifact to copy to files/. "
        "Repeatable for multi-step build processes.",
    )
    parser.add_argument(
        "--work-folder",
        help="Path to workFolder relative to the repo root. If not given, "
        "read from .claude/pv-context.json (default '/').",
    )
    args = parser.parse_args()

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    root = repo_root()
    work_folder_rel = args.work_folder or load_work_folder(root)
    versions_dir = resolve_versions_dir(root, work_folder_rel)

    version_files_dir = versions_dir / args.xxxx / "files"
    if not version_files_dir.is_dir():
        raise SystemExit(
            f"{version_files_dir} doesn't exist. Run init-version-folder.py "
            "first to create the version's folder."
        )

    sources = [root / src for src in args.source]
    for source_path, src_rel in zip(sources, args.source):
        if not source_path.is_file():
            raise SystemExit(f"Source file doesn't exist: {src_rel}")

    copied: list[str] = []
    for source_path in sources:
        dest_path = version_files_dir / source_path.name
        shutil.copy2(source_path, dest_path)
        copied.append(dest_path.relative_to(root).as_posix())

    json.dump({"copied": copied}, sys.stdout, ensure_ascii=False)
    print()


if __name__ == "__main__":
    main()
